/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectCategory = IDL.Variant({
  'graphicDesign' : IDL.Null,
  'uiUx' : IDL.Null,
  'branding' : IDL.Null,
});
export const ProjectId = IDL.Nat;
export const ContactMessage = IDL.Record({
  'id' : IDL.Int,
  'name' : IDL.Text,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Project = IDL.Record({
  'id' : ProjectId,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : ProjectCategory,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Text, ProjectCategory, IDL.Text],
      [ProjectId],
      [],
    ),
  'deleteProject' : IDL.Func([ProjectId], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([ProjectId], [Project], ['query']),
  'getService' : IDL.Func([IDL.Nat], [Service], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listProjects' : IDL.Func(
      [IDL.Opt(ProjectCategory)],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'markContactAsRead' : IDL.Func([IDL.Int], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProject' : IDL.Func(
      [ProjectId, IDL.Text, IDL.Text, ProjectCategory, IDL.Text],
      [],
      [],
    ),
  'updateService' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectCategory = IDL.Variant({
    'graphicDesign' : IDL.Null,
    'uiUx' : IDL.Null,
    'branding' : IDL.Null,
  });
  const ProjectId = IDL.Nat;
  const ContactMessage = IDL.Record({
    'id' : IDL.Int,
    'name' : IDL.Text,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Project = IDL.Record({
    'id' : ProjectId,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : ProjectCategory,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Text, ProjectCategory, IDL.Text],
        [ProjectId],
        [],
      ),
    'deleteProject' : IDL.Func([ProjectId], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([ProjectId], [Project], ['query']),
    'getService' : IDL.Func([IDL.Nat], [Service], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listProjects' : IDL.Func(
        [IDL.Opt(ProjectCategory)],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'markContactAsRead' : IDL.Func([IDL.Int], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProject' : IDL.Func(
        [ProjectId, IDL.Text, IDL.Text, ProjectCategory, IDL.Text],
        [],
        [],
      ),
    'updateService' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };