/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Project {
  'id' : ProjectId,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'imageUrl' : string,
  'category' : ProjectCategory,
}
export type ProjectCategory = { 'graphicDesign' : null } |
  { 'uiUx' : null } |
  { 'branding' : null };
export type ProjectId = bigint;
export interface Service {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'price' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addService' : ActorMethod<[string, string, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<
    [string, string, ProjectCategory, string],
    ProjectId
  >,
  'deleteProject' : ActorMethod<[ProjectId], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'getAllContacts' : ActorMethod<[], Array<ContactMessage>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[ProjectId], Project>,
  'getService' : ActorMethod<[bigint], Service>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listProjects' : ActorMethod<[[] | [ProjectCategory]], Array<Project>>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'markContactAsRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContact' : ActorMethod<[string, string, string], undefined>,
  'updateProject' : ActorMethod<
    [ProjectId, string, string, ProjectCategory, string],
    undefined
  >,
  'updateService' : ActorMethod<[bigint, string, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];